server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RemoveRequestHeader=Cookie
          routes:
            - id: customer-service
              uri: http://localhost:8083
              predicates:
                - Path=/customers/**
              filters: []
            - id: analytic-service
              uri: http://localhost:8082
              predicates:
                - Path=/analytic/**
              filters: []
            - id: history-service
              uri: http://localhost:8084
              predicates:
                - Path=/history/**
              filters: []

